export PATH="$PATH:./bin"
export PATH="$PATH:$HOME/.rbenv/shims"
export PATH="$PATH:$HOME/.rbenv/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/local/sbin"
#export PATH="$PATH:$HOME/.sfs"
export PATH="$PATH:$ZSH/bin"
#export PATH="$PATH:$HOME/src/android-sdks/platform-tools"
#export PATH="$PATH:$HOME/src/android-sdks/tools"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:$HOME/.cabal/bin"
